version: '3.8'

services:
  php:
    build:
      dockerfile: php-dockerfile
    volumes:
      - './php-files:/var/www/html'
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    links:
      - 'php'
    volumes:
      - './php-files:/var/www/html'
      - './nginx-conf:/etc/nginx/conf.d'
    depends_on:
      - php

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - 'mysqldata:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb

volumes:
  mysqldata:

